im:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  # 心跳超时时间，单位毫秒
  heartBeatTime: 3000

  redis:
    mode: single
    database: 0
    #    password: 123456
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 127.0.0.1:6379